services:
  - type: web
    name: musteri-anketi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DATABASE_URL
        fromDatabase:
          name: anket-db
          property: connectionString

databases:
  - name: anket-db
    databaseName: anket
    user: anket_user
    plan: free
